language: generic

sudo: required

services:
  - docker

before_install:
  - docker network create rebump-net
  - docker pull tile38/tile38:1.11.1
  - docker run -d --name=tile38 tile38/tile38
  - docker network connect --alias=tile38 rebump-net tile38
  - docker pull couchdb:2.1
  - docker run -d --name=couchdb couchdb
  - docker network connect --alias=couchdb rebump-net couchdb
  - docker pull loderunner/rebump

env:
  - DOCKER_OPTS="$DOCKER_OPTS --mount=type=bind,src=$PWD,dst=/go/src/github.com/loderunner/rebump"

jobs:
  include:
    - script:
      - docker run $DOCKER_OPTS loderunner/rebump /bin/bash -c "make && ./rebump -V"
    - script:
      - docker run $DOCKER_OPTS loderunner/rebump make test
    - script:
      - docker run $DOCKER_OPTS loderunner/rebump make race
    - script:
      - docker run $DOCKER_OPTS loderunner/rebump make msan
    - script:
      - docker run $DOCKER_OPTS loderunner/rebump make lint

