language: generic

sudo: required

services:
  - docker

before_install:
  - docker pull tile38/tile38:1.11.1
  - docker run -d -p 9851:9851 tile38/tile38
  - docker pull couchdb:2.1
  - docker run -d -p 5984:5984 -d couchdb
  - docker pull loderunner/rebump

jobs:
  include:
    - script:
      - docker run loderunner/rebump  /bin/bash -c "make"
    - script:
      - docker run loderunner/rebump  /bin/bash -c "make test"
    - script:
      - docker run loderunner/rebump  /bin/bash -c "make race"
    - script:
      - docker run loderunner/rebump  /bin/bash -c "make msan"
    - script:
      - docker run loderunner/rebump  /bin/bash -c "make lint"

