FROM golang:1.10
LABEL authors="Charles Francoise <charles.francoise@gmail.com>"

ENV workdir=/go/src/github.com/loderunner/rebump

RUN mkdir -p ${workdir}
WORKDIR ${workdir}

# Install golint + grpc-gateway plugin for protoc + goose + caddy
RUN go get -u github.com/golang/lint/golint \
    && go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway \
    && go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger \
    && go get -u github.com/golang/protobuf/protoc-gen-go

# Install clang from debian repository
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - \
    && echo "deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch-5.0 main" | tee -a /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends clang-5.0

# Set Clang as default CC
ENV set_clang /etc/profile.d/set-clang-cc.sh
RUN echo "export CC=clang-5.0" | tee -a ${set_clang} && chmod a+x ${set_clang}

# Install utilities
RUN apt-get install -y --no-install-recommends unzip rsync

# Install protoc
RUN wget -O /tmp/protoc-3.5.1-linux-x86_64.zip https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip \
    && mkdir -p /tmp/protoc3 \
    && unzip /tmp/protoc-3.5.1-linux-x86_64.zip -d /tmp/protoc3 \
    && rsync -az /tmp/protoc3/bin/ /usr/bin/ \
    && rsync -az /tmp/protoc3/include/ /usr/include/

# Cleanup
RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
