// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/rebump.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api/rebump.proto

It has these top-level messages:
	Bump
	Location
	CreateBumpRequest
	GetNearbyRequest
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Bump struct {
	Name     string       `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Location *Location    `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
	Url      string       `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	Secret   *Bump_Secret `protobuf:"bytes,4,opt,name=secret" json:"secret,omitempty"`
}

func (m *Bump) Reset()                    { *m = Bump{} }
func (m *Bump) String() string            { return proto.CompactTextString(m) }
func (*Bump) ProtoMessage()               {}
func (*Bump) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Bump) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Bump) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Bump) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Bump) GetSecret() *Bump_Secret {
	if m != nil {
		return m.Secret
	}
	return nil
}

type Bump_Secret struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *Bump_Secret) Reset()                    { *m = Bump_Secret{} }
func (m *Bump_Secret) String() string            { return proto.CompactTextString(m) }
func (*Bump_Secret) ProtoMessage()               {}
func (*Bump_Secret) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Bump_Secret) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Location struct {
	Latitude  float64 `protobuf:"fixed64,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Location) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type CreateBumpRequest struct {
	Location *Location `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
}

func (m *CreateBumpRequest) Reset()                    { *m = CreateBumpRequest{} }
func (m *CreateBumpRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateBumpRequest) ProtoMessage()               {}
func (*CreateBumpRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateBumpRequest) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type GetNearbyRequest struct {
	Location *Location `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
}

func (m *GetNearbyRequest) Reset()                    { *m = GetNearbyRequest{} }
func (m *GetNearbyRequest) String() string            { return proto.CompactTextString(m) }
func (*GetNearbyRequest) ProtoMessage()               {}
func (*GetNearbyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetNearbyRequest) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func init() {
	proto.RegisterType((*Bump)(nil), "api.Bump")
	proto.RegisterType((*Bump_Secret)(nil), "api.Bump.Secret")
	proto.RegisterType((*Location)(nil), "api.Location")
	proto.RegisterType((*CreateBumpRequest)(nil), "api.CreateBumpRequest")
	proto.RegisterType((*GetNearbyRequest)(nil), "api.GetNearbyRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Rebump service

type RebumpClient interface {
	CreateBump(ctx context.Context, in *CreateBumpRequest, opts ...grpc.CallOption) (*Bump, error)
	GetNearby(ctx context.Context, in *GetNearbyRequest, opts ...grpc.CallOption) (*Bump, error)
}

type rebumpClient struct {
	cc *grpc.ClientConn
}

func NewRebumpClient(cc *grpc.ClientConn) RebumpClient {
	return &rebumpClient{cc}
}

func (c *rebumpClient) CreateBump(ctx context.Context, in *CreateBumpRequest, opts ...grpc.CallOption) (*Bump, error) {
	out := new(Bump)
	err := grpc.Invoke(ctx, "/api.Rebump/CreateBump", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rebumpClient) GetNearby(ctx context.Context, in *GetNearbyRequest, opts ...grpc.CallOption) (*Bump, error) {
	out := new(Bump)
	err := grpc.Invoke(ctx, "/api.Rebump/GetNearby", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Rebump service

type RebumpServer interface {
	CreateBump(context.Context, *CreateBumpRequest) (*Bump, error)
	GetNearby(context.Context, *GetNearbyRequest) (*Bump, error)
}

func RegisterRebumpServer(s *grpc.Server, srv RebumpServer) {
	s.RegisterService(&_Rebump_serviceDesc, srv)
}

func _Rebump_CreateBump_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBumpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RebumpServer).CreateBump(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Rebump/CreateBump",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RebumpServer).CreateBump(ctx, req.(*CreateBumpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rebump_GetNearby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNearbyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RebumpServer).GetNearby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Rebump/GetNearby",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RebumpServer).GetNearby(ctx, req.(*GetNearbyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Rebump_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Rebump",
	HandlerType: (*RebumpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBump",
			Handler:    _Rebump_CreateBump_Handler,
		},
		{
			MethodName: "GetNearby",
			Handler:    _Rebump_GetNearby_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/rebump.proto",
}

func init() { proto.RegisterFile("api/rebump.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0xcd, 0x4a, 0xfb, 0x40,
	0x10, 0x67, 0xdb, 0xfe, 0x43, 0x33, 0x7f, 0x95, 0x38, 0xa8, 0x84, 0xd0, 0x43, 0xc9, 0xa9, 0x7a,
	0x48, 0xa1, 0xde, 0x04, 0x05, 0xad, 0xe0, 0x45, 0x3c, 0xc4, 0x27, 0xd8, 0xd6, 0xa1, 0x04, 0xd3,
	0xdd, 0x75, 0xbb, 0x39, 0xf4, 0xea, 0x13, 0x08, 0x9e, 0x7d, 0x2a, 0x5f, 0xc1, 0x07, 0x91, 0x9d,
	0xc4, 0xd4, 0x0f, 0x10, 0xbc, 0x4d, 0x7e, 0x5f, 0xf3, 0xdb, 0x0c, 0x44, 0xd2, 0x14, 0x63, 0x4b,
	0xb3, 0x6a, 0x69, 0x32, 0x63, 0xb5, 0xd3, 0xd8, 0x95, 0xa6, 0x48, 0x06, 0x0b, 0xad, 0x17, 0x25,
	0x8d, 0x3d, 0x2b, 0x95, 0xd2, 0x4e, 0xba, 0x42, 0xab, 0x55, 0x2d, 0x49, 0x5f, 0x04, 0xf4, 0x2e,
	0xaa, 0xa5, 0x41, 0x84, 0x9e, 0x92, 0x4b, 0x8a, 0xc5, 0x50, 0x8c, 0xc2, 0x9c, 0x67, 0x3c, 0x84,
	0x7e, 0xa9, 0xe7, 0xac, 0x8f, 0x3b, 0x43, 0x31, 0xfa, 0x3f, 0xd9, 0xce, 0xa4, 0x29, 0xb2, 0xeb,
	0x06, 0xcc, 0x5b, 0x1a, 0x23, 0xe8, 0x56, 0xb6, 0x8c, 0xbb, 0xec, 0xf6, 0x23, 0x8e, 0x20, 0x58,
	0xd1, 0xdc, 0x92, 0x8b, 0x7b, 0x6c, 0x8d, 0xd8, 0xea, 0x77, 0x65, 0xb7, 0x8c, 0xe7, 0x0d, 0x9f,
	0x24, 0x10, 0xd4, 0x88, 0x4f, 0xb9, 0xa7, 0x75, 0xd3, 0xc1, 0x8f, 0xe9, 0x25, 0xf4, 0x3f, 0xb6,
	0x61, 0x02, 0xfd, 0x52, 0xba, 0xc2, 0x55, 0x77, 0x75, 0x4d, 0x91, 0xb7, 0xdf, 0x38, 0x80, 0xb0,
	0xd4, 0x6a, 0x51, 0x93, 0x1d, 0x26, 0x37, 0x40, 0x7a, 0x06, 0xbb, 0x53, 0x4b, 0xd2, 0x91, 0x5f,
	0x9f, 0xd3, 0x43, 0x45, 0x2b, 0xf7, 0xe5, 0x75, 0xe2, 0xd7, 0xd7, 0xa5, 0xa7, 0x10, 0x5d, 0x91,
	0xbb, 0x21, 0x69, 0x67, 0xeb, 0xbf, 0xdb, 0x27, 0x4f, 0x02, 0x82, 0x9c, 0x0f, 0x83, 0xe7, 0x00,
	0x9b, 0x26, 0x78, 0xc0, 0x8e, 0x1f, 0xd5, 0x92, 0xb0, 0xfd, 0x57, 0x69, 0xf4, 0xf8, 0xfa, 0xf6,
	0xdc, 0x81, 0xf4, 0xdf, 0xd8, 0xfb, 0x4f, 0xc4, 0x11, 0x4e, 0x21, 0x6c, 0xcb, 0xe0, 0x3e, 0x2b,
	0xbf, 0x97, 0xfb, 0x1c, 0xb0, 0xc7, 0x01, 0x3b, 0xb8, 0x55, 0x07, 0x28, 0xd6, 0xcd, 0x02, 0x3e,
	0xff, 0xf1, 0x7b, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x9f, 0x21, 0x3c, 0x35, 0x02, 0x00, 0x00,
}
